<?php
/**
 * Joomla component file renamer
 * Generated by Rector Joomla upgrade rules on 2026-09-06 20:31:18
 *
 * This script moves files to their new PSR-4 locations.
 * Run it once from the command line:
 *
 *   php rename.php
 *
 * All paths are relative to the directory containing this file.
 */

declare(strict_types=1);

$renames = [
    'example.php'                                                => 'src/Extension/Example.php',
];

$scriptDir = rtrim(str_replace('\\', '/', __DIR__), '/');
$errors    = 0;
$skipped   = 0;
$moved     = 0;

foreach ($renames as $from => $to)
{
    $absoluteFrom = $scriptDir . '/' . $from;
    $absoluteTo   = $scriptDir . '/' . $to;

    if (!file_exists($absoluteFrom))
    {
        echo "SKIP (already moved or missing): {$from}\n";
        $skipped++;
        continue;
    }

    $dir = dirname($absoluteTo);

    if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir))
    {
        echo "ERROR (cannot create directory): {$dir}\n";
        $errors++;
        continue;
    }

    if (rename($absoluteFrom, $absoluteTo))
    {
        echo "OK: {$from}\n => {$to}\n";
        $moved++;
    }
    else
    {
        echo "ERROR (rename failed): {$from}\n";
        $errors++;
    }
}

echo "\nDone: {$moved} moved, {$skipped} skipped, {$errors} errors.\n";